#!/usr/bin/env ruby
require 'safe_pusher'

ARGV.each do |command|
  case command
  when 'test', 't'
    puts '##########################'.yellow
    puts '## Testing new files... ##'.yellow
    puts '##########################'.yellow
    results = SafePusher::RspecRunner.new.call

    exit results unless results == 0
  when 'lint', 'l'
    puts '#######################'.yellow
    puts '## Running linter... ##'.yellow
    puts '#######################'.yellow

    results = SafePusher::ProntoRunner.new.call

    exit results unless results == 0
  when 'open', 'o'
    puts '#########################################'.yellow
    puts '## Opening a pull request on Github... ##'.yellow
    puts '#########################################'.yellow

    results = SafePusher::GithubRunner.new.open

    exit results unless results == 0
  when 'push', 'p'
    puts '##########################'.yellow
    puts '## Pushing to Github... ##'.yellow
    puts '##########################'.yellow

    results = SafePusher::GithubRunner.new.push

    exit results unless results == 0
  when 'push_and_open', 'po'
    puts '##########################'.yellow
    puts '## Pushing to Github... ##'.yellow
    puts '##########################'.yellow

    results = SafePusher::GithubRunner.new.push_and_open

    exit results unless results == 0
  else
    SafePusher::CLI.new.display_help
  end
end

# SafePusher::CLI.start
